# Generated by Django 5.2.4 on 2025-09-07 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_transcript_doubt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listItem', models.TextField()),
                ('listItemStatus', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('ongoing', 'Ongoing')], default='incomplete', max_length=10)),
                ('listOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
